<?php

namespace App\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\Users;
use App\Entity\Points;
use App\Service\VKAPI;

class SyncDB extends Command
{
    // the name of the command (the part after "bin/console")
    protected static $defaultName = 'app:sync-db';

    private $em;

    private $key = 'OMNK8U0Y0C77DBRGD7REYT3QCDRTOE';

    public function __construct(EntityManagerInterface $entityManager, ?string $name = null)
    {
        parent::__construct($name);

        $this->em = $entityManager;
    }

    protected function configure()
    {
        // ...
    }

    private function userIds($users)
    {
        $userIds = [];

        foreach ($users as $item) {
            $userIds[] = $item->userId;
        }

        return array_unique($userIds);
    }

    private function findFromProfiles($userId, array $profiles)
    {
        foreach ($profiles as $profile) {
            if ($profile->id == $userId) return $profile;
        }

        return null;
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $userActivities = json_decode(file_get_contents('https://api.letscover.me/activity/users?key=' . $this->key));
        $userActivitiesChunked = array_chunk($userActivities, 500);
        $recordedUsers = 0;

        echo 'Letscover users: ' . count($userActivities) . PHP_EOL;

        foreach ($userActivitiesChunked as $usersChunk) {
            $profiles = VKAPI::usersGet($this->userIds($usersChunk));

            echo 'Request: ' . count($usersChunk). ' response: ' . count($profiles) . PHP_EOL;

            sleep(1);

            foreach ($usersChunk as $item) {
                $profile = $this->findFromProfiles($item->userId, $profiles);

                try {
                    if (is_null($profile)) {
                        $profile = VKAPI::usersGet($item->userId)[0] ?? null;
                        if (is_null($profile)) throw new \Exception('Error user_id = ' . $item->userId . ' not found');
                        sleep(1);
                    }

                    $user = (new Users())
                        ->setUserId($item->userId)
                        ->setFirstName($item->firstName)
                        ->setLastName($item->lastName)
                        ->setPhoto100($profile->photo_100)
                        ->setBalance($item->points);

                    $point = (new Points())
                        ->setVerify(1)
                        ->setAmount($item->points)
                        ->setDateAt(new \DateTime())
                        ->setUser($user)
                        ->setAutogenerated(true);

                    $this->em->persist($user);
                    $this->em->persist($point);
                    $this->em->flush();

                    $recordedUsers++;
                } catch (\Exception $e) {
                    echo $e->getMessage() . PHP_EOL;
                }
            }
        }

        /*$user = (new Users())
            ->setUserId(271016769)
            ->setFirstName('Leonid')
            ->setLastName('Chernov')
            ->setPhoto100('https://sun1-99.userapi.com/impf/c840222/v840222710/6dd6a/exeT_N1B8L0.jpg?size=50x0&quality=88&crop=311,0,294,294&sign=447485e561f7006e584835b632a3babb&ava=1')
            ->setBalance(333);

        $point = (new Points())
            ->setVerify(1)
            ->setAmount(333)
            ->setDateAt(new \DateTime())
            ->setUser($user);

        $this->em->persist($user);
        $this->em->persist($point);
        $this->em->flush();*/

        echo 'Users stored: ' . $recordedUsers . PHP_EOL;

        return Command::SUCCESS;
    }
}