<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20201028110451 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        $this->addSql('ALTER TABLE points DROP autogenerated');
    }

    public function down(Schema $schema) : void
    {
        $this->addSql('ALTER TABLE points ADD autogenerated TINYINT(1) DEFAULT \'0\' NOT NULL');
    }
}
